import spotipy
from .spotify_auth import sp

def create_playlist(playlist_name: str, song_uris: list):
    '''creates a playlist with the name provided by the user and adds the songs
    provided by the user.'''
    try:
        user_id = sp.current_user()['id']
    except spotipy.SpotifyException as e:
        print(f"Error getting user ID: {e}")
        return

    try:
        playlist = sp.user_playlist_create(user=user_id,
                                           name=playlist_name,
                                           public=True,
                                           collaborative=False,
                                           description='generated by Dive Back In Time app')
    except spotipy.SpotifyException as e:
        print(f"Error creating playlist: {e}")
        return

    try:
        sp.user_playlist_add_tracks(user=user_id, playlist_id=playlist['id'], tracks=song_uris)
    except spotipy.SpotifyException as e:
        print(f"Error adding tracks to playlist: {e}")
        return
